--I want to finish a project for once so I'm going to try and keep this simple
--I then proceeded to not keep it simple
CREATE TABLE IF NOT EXISTS teams (
    id SERIAL PRIMARY KEY,
    name VARCHAR(5) NOT NULL);

CREATE TABLE IF NOT EXISTS players (
    id INTEGER PRIMARY KEY,
    firstname VARCHAR(32),
    lastname VARCHAR(32),
    team_id INTEGER,
    position VARCHAR(5),
    injury VARCHAR(255),
    gamelog_url TEXT,
    FOREIGN KEY (team_id) REFERENCES teams(id));

CREATE TABLE IF NOT EXISTS player_season_advanced_stats (
    player_id INTEGER NOT NULL,
    season INTEGER NOT NULL,
    team_id INTEGER NOT NULL,
    games INTEGER,
    bad_pass_pct NUMERIC(5,2),
    dropped INTEGER,
    dropped_rate NUMERIC(5,2),
    avg_pass_yac NUMERIC(5,2),
    avg_throw_depth NUMERIC(5,2),
    sack_rate NUMERIC(5,2),
    broken_tackles INTEGER,
    broken_tackle_pct NUMERIC(5,2),
    pos_run_pct NUMERIC(5,2),
    inside_run_pct NUMERIC(5,2),
    outside_run_pct NUMERIC(5,2),
    rush_td_pct NUMERIC(5,2),
    rush_yac INTEGER,
    avg_rush_yac NUMERIC(5,2),
    rush_yac_pct NUMERIC(5,2),
    air_yards INTEGER,
    completed_air_yards INTEGER,
    ay_snap NUMERIC(5,2),
    yac INTEGER,
    avg_yac NUMERIC(5,2),
    rec_yac_pct NUMERIC(5,2),
    avg_completed_air_yards NUMERIC(5,2),
    a_dot NUMERIC(5,2),
    catch_rate NUMERIC(5,2),
    drop_rate NUMERIC(5,2),
    air_yard_share NUMERIC(5,2),
    target_share NUMERIC(5,2),
    drawn_pi INTEGER,
    offensive_pi INTEGER,
    yards_pi INTEGER,
    yards_lost_to_penalties INTEGER,
    routes INTEGER,
    tprr NUMERIC(5,2),
    yprr NUMERIC(5,2),
    PRIMARY KEY (player_id, season, team_id),
    FOREIGN KEY (player_id) REFERENCES players(id)
);

CREATE TABLE IF NOT EXISTS player_season_basic_stats (
    player_id INTEGER NOT NULL,
    season INTEGER NOT NULL,
    team_id INTEGER NOT NULL,
    age INTEGER,
    games INTEGER,
    snaps_off INTEGER,
    snaps_def INTEGER,
    snaps_special INTEGER,
    fumbles_off INTEGER,
    fumbles_lost INTEGER,
    pass_att INTEGER,
    pass_comp INTEGER,
    pass_pct NUMERIC(5,2),
    pass_yds INTEGER,
    pass_td INTEGER,
    pass_int INTEGER,
    pass_avg NUMERIC(5,2),
    pass20 INTEGER,
    pass40 INTEGER,
    pass300 INTEGER,
    pass350 INTEGER,
    pass400 INTEGER,
    rush_att INTEGER,
    rush_yds INTEGER,
    rush_td INTEGER,
    rush_avg NUMERIC(5,2),
    rush20 INTEGER,
    rush40 INTEGER,
    rush100 INTEGER,
    rush150 INTEGER,
    rush200 INTEGER,
    rec INTEGER,
    rec_yds INTEGER,
    rec_td INTEGER,
    rec_avg NUMERIC(5,2),
    rec20 INTEGER,
    rec40 INTEGER,
    rec100 INTEGER,
    rec150 INTEGER,
    rec200 INTEGER,
    targets INTEGER,
    yds_target NUMERIC(5,2),
    drops INTEGER,
    kick_ret_yds INTEGER,
    kick_ret_td INTEGER,
    punt_ret_yds INTEGER,
    punt_ret_td INTEGER,
    PRIMARY KEY (player_id, season, team_id),
    FOREIGN KEY (player_id) REFERENCES players(id)
);

CREATE TABLE IF NOT EXISTS player_season_fantasy_rz_stats (
    player_id INTEGER NOT NULL,
    season INTEGER NOT NULL,
    team_id INTEGER NOT NULL,
    age INTEGER,
    games INTEGER,
    standard NUMERIC(5,2),
    halfppr NUMERIC(5,2),
    ppr NUMERIC(5,2),
    rz_touches_team_pct NUMERIC(5,2),
    rz_touches20 INTEGER,
    rz_touches10 INTEGER,
    rz_touches5 INTEGER,
    rz_touches20conv NUMERIC(5,2),
    rz_touches10conv NUMERIC(5,2),
    rz_touches5conv NUMERIC(5,2),
    rz_pass_team_pct NUMERIC(5,2),
    rz_pass20 INTEGER,
    rz_pass10 INTEGER,
    rz_pass5 INTEGER,
    rz_pass20conv NUMERIC(5,2),
    rz_pass10conv NUMERIC(5,2),
    rz_pass5conv NUMERIC(5,2),
    td_pct NUMERIC(5,2),
    int_pct NUMERIC(5,2),
    sacks NUMERIC(5,2),
    rating NUMERIC(5,2),
    rz_rec_team_pct NUMERIC(5,2),
    rz_rec20 INTEGER,
    rz_rec10 INTEGER,
    rz_rec5 INTEGER,
    rz_rec20conv NUMERIC(5,2),
    rz_rec10conv NUMERIC(5,2),
    rz_rec5conv NUMERIC(5,2),
    rz_rush_team_pct NUMERIC(5,2),
    rz_rush20 INTEGER,
    rz_rush10 INTEGER,
    rz_rush5 INTEGER,
    rz_rush20conv NUMERIC(5,2),
    rz_rush10conv NUMERIC(5,2),
    rz_rush5conv NUMERIC(5,2),
    rec_per_game NUMERIC(5,2),
    rec_yards_per_game NUMERIC(5,2),
    rush_att_per_game NUMERIC(5,2),
    rush_yards_per_game NUMERIC(5,2),
    touches_per_game NUMERIC(5,2),
    yards_per_game NUMERIC(5,2),
    PRIMARY KEY (player_id, season, team_id),
    FOREIGN KEY (player_id) REFERENCES players(id)
);

CREATE TABLE IF NOT EXISTS player_gamelogs (
    player_id INTEGER NOT NULL,
    season INTEGER NOT NULL,
    game_id INTEGER, 
    week VARCHAR(10) NOT NULL,             -- Can be a number or 'BYE'
    opp VARCHAR(10),    -- Opponent team
    game_url TEXT,
    is_home BOOLEAN,
    dnp BOOLEAN,            
    snaps_off INTEGER,
    snaps_def INTEGER,
    snaps_special INTEGER,
    standard_pts NUMERIC(5,2),
    halfppr_pts NUMERIC(5,2),
    ppr_pts NUMERIC(5,2),
    fanduel_pts NUMERIC(5,2),
    draftkings_pts NUMERIC(5,2),
    yahoo_pts NUMERIC(5,2),
    pass_att INTEGER,
    pass_comp INTEGER,
    pass_pct NUMERIC(5,2),
    pass_yds INTEGER,
    pass_td INTEGER,
    pass_int INTEGER,
    pass_avg NUMERIC(5,2),
    pass20 INTEGER,
    pass40 INTEGER,
    rec INTEGER,
    rec_yds INTEGER,
    rec_td INTEGER,
    rec_avg NUMERIC(5,2),
    rec20 INTEGER,
    rec40 INTEGER,
    targets INTEGER,
    yds_target NUMERIC(5,2),
    routes INTEGER,
    tprr NUMERIC(5,2),
    yprr NUMERIC(5,2),
    rush_att INTEGER,
    rush_yds INTEGER,
    rush_td INTEGER,
    rush_avg NUMERIC(5,2),
    rush20 INTEGER,
    rush40 INTEGER,
    fumbles_off INTEGER,
    fumbles_lost INTEGER,
    rz_pass20 INTEGER,
    rz_pass10 INTEGER,
    rz_pass5 INTEGER,
    rz_rush20 INTEGER,
    rz_rush10 INTEGER,
    rz_rush5 INTEGER,
    rz_targets20 INTEGER,
    rz_targets10 INTEGER,
    rz_targets5 INTEGER,
    kick_ret_yds INTEGER,
    kick_ret_td INTEGER,
    punt_ret_yds INTEGER,
    punt_ret_td INTEGER,
    standard_def INTEGER,
    halfppr_def INTEGER,
    ppr_def INTEGER,
    fanduel_def INTEGER,
    draftkings_def INTEGER,
    yahoo_def INTEGER,
    PRIMARY KEY (player_id, season, week),
    FOREIGN KEY (player_id) REFERENCES players(id)
);

CREATE TABLE IF NOT EXISTS player_alignment_stats (
    player_id INTEGER NOT NULL,
    season INTEGER NOT NULL,
    alignment VARCHAR(50) NOT NULL,   -- e.g., 'Left Outside', 'Right Slot'
    plays INTEGER,
    pct NUMERIC(5,2),
    rec INTEGER,
    yards INTEGER,
    td INTEGER,
    yac INTEGER,
    drops INTEGER,
    standard_pp NUMERIC(5,2),
    halfppr_pp NUMERIC(5,2),
    ppr_pp NUMERIC(5,2),
    standard NUMERIC(5,2),
    halfppr NUMERIC(5,2),
    ppr NUMERIC(5,2),
    PRIMARY KEY (player_id, season, alignment),
    FOREIGN KEY (player_id) REFERENCES players(id)
);    


CREATE TABLE IF NOT EXISTS player_season_splits (
    player_id INTEGER NOT NULL,
    season INTEGER NOT NULL,
    split_id VARCHAR(50) NOT NULL, -- Unique identifier for the type of split (e.g., 'H', 'A', 'Grass', '1stHalf', 'W')
    split VARCHAR(100), -- Descriptive name of the split (e.g., 'Home', 'Away', 'Grass', '1st Half')
    fumbles INTEGER,
    fpts NUMERIC(5,2),
    fpts_half NUMERIC(5,2),
    fpts_ppr NUMERIC(5,2),
    comp INTEGER,
    pass_att INTEGER,
    comp_pct NUMERIC(5,2),
    pass_yards INTEGER,
    pass_td INTEGER,
    pass_td_pct NUMERIC(5,2),
    int INTEGER,
    int_pct NUMERIC(5,2),
    bad_pass INTEGER,
    rush_att INTEGER,
    rush_yards INTEGER,
    rush_td INTEGER,
    rush_yac INTEGER,
    broken_tackles INTEGER,
    inside_runs INTEGER,
    outside_runs INTEGER,
    runs_stuffed INTEGER,
    targ INTEGER,
    rec INTEGER,
    rec_td INTEGER,
    rec_yards INTEGER,
    comp_air_yards INTEGER,
    rec_yac INTEGER,
    drops INTEGER,
    a_dot NUMERIC(5,2),
    rec_ypc NUMERIC(5,2),
    PRIMARY KEY (player_id, season, split_id),
    FOREIGN KEY (player_id) REFERENCES players(id)
);
